version: 'build #{build}'

os: Visual Studio 2015

environment:
  matrix:
    - backend:  ninja
      compiler: mingw
    - backend:  ninja
      compiler: msvc2015
    - backend:  vs2015
      compiler: msvc2015

platform:
  - x86
  - x64

configuration:
  - debug
  - release

# scripts that are called at very beginning, before repo cloning
init:
  - set "PYTHON_HOME=C:\Python35-x64"
  - set "PATH=%PYTHON_HOME%;%PYTHON_HOME%\Scripts;%PATH%"
  - pip3 install meson
  - meson --version
  - cinst ninja
  - ninja --version
  - del "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"

# to run your custom scripts instead of automatic MSBuild
build_script:
  - set build=build
  - appveyor.bat
  - cd build && if %platform%==x86 (
      7z a hello-%compiler%-%backend%-windows.zip hello.exe
    ) else (
      7z a hello-%compiler%-%backend%-windows64.zip hello.exe
    ) && cd ..

# to run your custom scripts instead of automatic tests
test_script:
  - build\hello

# artifacts configuration
artifacts:
  - path: build\hello-*.zip
    name: build

# Deploy to GitHub Releases
deploy:
  provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  description: 'v$(APPVEYOR_REPO_TAG_NAME)'
  artifact: build
  auth_token:
    secure: "2l/602m6FkqAB9TTIAkPX3Erfwg9jVTlf/Inmf2dWcbOrJJzK/WrCUIgY3B4ngly"
  draft: false
  prerelease: false
  on:
    configuration: release
    appveyor_repo_tag: true
