version: 'build #{build}'

os: Visual Studio 2015

environment:
  matrix:
    - Compiler: linux-gcc
    - Compiler: linux-arm-gcc
    - Compiler: windows-mingw
    - Compiler: windows-msvc2015
    - Compiler: windows-msvc2015-msbuild   
  
platform:
  - 32
  - 64

configuration:
  - debug
  - release

# scripts that are called at very beginning, before repo cloning
init:
  - set "PYTHON_HOME=C:\Python35-x64"
  - set "PATH=%PYTHON_HOME%;%PYTHON_HOME%\Scripts;%PATH%"
  - pip3 install meson
  - meson --version
  - cinst ninja
  - ninja --version
  - if %compiler:windows-=%==%compiler% (pushd c:\cygwin64 && appveyor DownloadFile https://github.com/msink/cygwin-cross-tools/raw/master/%compiler%-%platform%.tar.xz && c:\cygwin64\bin\bash -lc "tar xJf /%compiler%-%platform%.tar.xz -C /" && popd)
  - del "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"

# to run your custom scripts instead of automatic MSBuild
build_script:
  - set build=build
  - appveyor.bat
  - if %compiler:windows-=%==%compiler% (
      pushd build && 7z a hello-%compiler%-%platform%.zip hello && popd
    ) else (
      pushd build && 7z a hello-%compiler%-%platform%.zip hello.exe && popd
    )

# to run your custom scripts instead of automatic tests
test_script:
  - echo build\hello

# artifacts configuration
artifacts:
  - path: build\hello-*.zip
    name: build

# Deploy to GitHub Releases
deploy:
  provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  description: 'v$(APPVEYOR_REPO_TAG_NAME)'
  artifact: build
  auth_token:
    secure: "2l/602m6FkqAB9TTIAkPX3Erfwg9jVTlf/Inmf2dWcbOrJJzK/WrCUIgY3B4ngly"
  draft: false
  prerelease: false
  on:
    configuration: release
    appveyor_repo_tag: true
