language: cpp
sudo: false
group: beta

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx

install:
# - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3 ninja; fi
  - pip3 install meson

script:
  - uname -a
  - gcc --version
  - meson --version
  - ninja --version




