language: cpp
sudo: false
group: beta

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3 ninja; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-linux.zip
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then unzip -q ninja-linux.zip
  - pip3 install meson

script:
  - uname -a
  - ls -l
  - gcc --version
  - meson --version
  - ninja --version




