sudo: false
group: beta

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3 ninja; fi

install:
  - uname -a

script:
  - uname -a
  - gcc --version
  - python3 --version
  - pip3 --version




