version: 1.0.{build}-{branch}

os: Visual Studio 2015

environment:
  matrix:
    - Compiler: msvc
    - Compiler: mingw

platform:
  - x86
  - x64

configuration:
  - debug
  - release

# scripts that are called at very beginning, before repo cloning
init:
  - set "PYTHON_HOME=C:\Python35-x64"
  - set "PATH=%PYTHON_HOME%;%PYTHON_HOME%\Scripts;%PATH%"
  - pip3 install meson
  - meson --version
  - cinst ninja
  - ninja --version
  - del "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"

# to run your custom scripts instead of automatic MSBuild
build_script:
  - set build=build
  - appveyor.bat

# to disable automatic tests
test: off

# scripts to run after build
after_build:
  - pushd build && 7z a hello-windows-%Platform%-%Compiler%.zip hello.exe && popd

# artifacts configuration
artifacts:
  - path: build\hello-*.zip

# Deploy to GitHub Releases
deploy:
  provider: GitHub
  auth_token:
    secure: "2l/602m6FkqAB9TTIAkPX3Erfwg9jVTlf/Inmf2dWcbOrJJzK/WrCUIgY3B4ngly"
  draft: false
  prerelease: false
  on:
    configuration: release
    appveyor_repo_tag: true
