version: 1.0.{build}-{branch}

os:
  - Visual Studio 2015

platform:
  - x64

environment:
  matrix:
    - compiler: msvc
      bit: 32
    - compiler: msvc
      bit: 64
    - compiler: mingw
      bit: 32
    - compiler: mingw
      bit: 64

# scripts that run after cloning repository
install:
  - set PYTHON_HOME=C:\Python35-x64
  - set PATH=%PYTHON_HOME%;%PYTHON_HOME%\Scripts;%PATH%
  - pip3 install meson
  - meson --version
  - cinst ninja
  - ninja --version

# scripts to run before build
before_build:
  - del "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"

# to run your custom scripts instead of automatic MSBuild
build_script:
  - appveyor.bat

# to disable automatic tests
test: off

# to disable deployment
deploy: off
