version: 1.0.{build}-{branch}

os: Visual Studio 2015

environment:
  matrix:
    - Compiler: msvc
    - Compiler: mingw

platform:
  - x86
  - x64

configuration:
  - debug
  - release

# scripts that are called at very beginning, before repo cloning
init:
  - set "PYTHON_HOME=C:\Python35-x64"
  - set "PATH=%PYTHON_HOME%;%PYTHON_HOME%\Scripts;%PATH%"
  - pip3 install meson
  - meson --version
  - cinst ninja
  - ninja --version
  - del "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"

# to run your custom scripts instead of automatic MSBuild
build_script:
  - appveyor.bat

# to disable automatic tests
test: off

# to disable deployment
deploy: off
